FROM node:20-alpine

WORKDIR /app

# Copia os gerenciadores de pacotes primeiro para aproveitar o cache do Docker
COPY package*.json ./

# Instala as dependências
RUN npm install

# Copia o restante dos arquivos do projeto
COPY . .

# Expõe a porta interna do Vite
EXPOSE 3000

# Executa o servidor de desenvolvimento
CMD ["npm", "run", "dev"]